# Generated by Django 5.0.3 on 2024-03-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Question_Text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('Answers_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Answer', models.CharField(max_length=255)),
                ('Is_Correct', models.BooleanField()),
                ('Question', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='BrainBusterApp.question')),
            ],
        ),
    ]
