# Generated by Django 5.0.3 on 2024-03-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainBusterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrainBusterApp.question'),
        ),
    ]
