# Generated by Django 5.0.3 on 2024-03-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainBusterApp', '0002_alter_answers_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='Is_Correct',
            field=models.BooleanField(default=False),
        ),
    ]
