# Generated by Django 5.0.3 on 2024-03-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainBusterApp', '0003_alter_answers_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Category',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.SET_DEFAULT, to='BrainBusterApp.category'),
        ),
    ]
