# Generated by Django 5.0.3 on 2024-03-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrainBusterApp', '0004_category_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Category',
        ),
    ]
