name: Push to Test-Branch

on:
  push:
    branches:
      - development

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      check_changes: ${{ steps.check_changes.outputs.changes }}
    steps:
    - name: Checkout des Codes
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}
      
    - name: Überprüfe Änderungen zwischen development und test
      id: check_changes
      run: |
        git fetch origin test
        if git diff --quiet origin/development origin/test; then
          echo "::set-output name=changes::No changes found"
        else
          echo "::set-output name=changes::Changes found"
        fi

  push-to-test:
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.check_changes == 'Changes found' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout des Codes
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}
      
    - name: Automatisches Pushen nach Test-Branch
      run: git push origin development:test
