name: CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, 3.11, 3.12]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r BrainBusterSite/requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

    
  build-artifact:
   runs-on: ubuntu-latest
   needs: unit-test  
   steps:
    - uses: actions/checkout@v3
    - name: Build Artifact
      run: | 
        echo "Building artifact..."
        python3 setup.py sdist bdist_wheel
        pip install -r BrainBusterSite/requirements.txt
        zip -r test-build.zip .
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-build
        path: test-build.zip
        
  deployment:
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
      - uses: actions/checkout@v2
      - name: Merge branches
        run: |
          git checkout main
          git merge test
          git push
