name: CI/CD

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r BrainBusterSite/requirements.txt
    - name: Run Tests
      run: |
        python BrainBusterSite/manage.py test BrainBusterApp.tests
        
  deploy:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Automatisches Pushen nach Main bei Erfolg
        if: success() && github.ref == 'refs/heads/test'
        uses: ./.github/workflows/build-test.yml@v1  
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: main
