name: Validate Code

on:
  push:
    branches:
      - "tyrone"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./BrainBusterSite/requirements.txt

      - name: Run Test
        run: python ./BrainBusterSite/manage.py test BrainBusterApp
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: npm install

      - name: Stylelinet
        run: npx stylelint "**/*.css"
