name: Run tests
  
on: 
  push:
    branches:
      - "tyrone"

jobs:
  super-linter:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: tyrone
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}