name: Auto-Push nach Test-Branch

on:
  push:
    branches:
      - development

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout des Codes
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Überprüfe Änderungen zwischen development und test
      id: check_changes
      run: |
        git fetch origin test
        git diff --name-only origin/development origin/test

  push-to-test:
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.check_changes != '' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout des Codes
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Automatisches Pushen nach Test-Branch
      run: git push origin development:test
